import type { Mission } from './types';

export const ALL_MISSIONS: Mission[] = [
  {
    id: 'restaurant-order',
    title: 'Commander au restaurant',
    scenario:
      'You are a waiter at a casual restaurant. The learner is a customer who just sat down.',
    objective: 'The customer orders at least a main dish and a drink.',
    requiredVocab: ['I would like', 'a table', 'the menu', 'please'],
    cefr: 'A2',
    turnLimit: 5,
    opener: "Good evening! Welcome. Here's the menu — can I get you something to drink first?",
  },
  {
    id: 'ask-directions',
    title: 'Demander son chemin',
    scenario: 'You are a friendly passer-by in a city. The learner is a lost tourist.',
    objective: 'The tourist asks how to reach the train station and confirms understanding.',
    requiredVocab: ['excuse me', 'how do I get to', 'turn left', 'is it far'],
    cefr: 'A2',
    turnLimit: 4,
    opener: 'Hi there! You look a little lost — do you need some help?',
  },
  {
    id: 'hotel-booking',
    title: "Réserver une chambre d'hôtel",
    scenario: 'You are a hotel receptionist. The learner wants to book a room.',
    objective: 'The guest books a room for specific dates and asks about breakfast.',
    requiredVocab: [
      'I would like to book',
      'a single/double room',
      'check-in',
      'is breakfast included',
    ],
    cefr: 'B1',
    turnLimit: 5,
    opener: 'Good afternoon, welcome to The Grand Hotel. How can I help you today?',
  },
  {
    id: 'self-introduction',
    title: 'Se présenter brièvement',
    scenario: 'You are a new colleague meeting the learner on their first day.',
    objective: 'The learner introduces themselves: name, role, and one interest.',
    requiredVocab: ['my name is', 'I work as', 'nice to meet you', 'I enjoy'],
    cefr: 'A2',
    turnLimit: 4,
    opener: "Hi! I don't think we've met — I'm Alex, I work in marketing. And you?",
  },
  {
    id: 'customer-complaint',
    title: 'Faire une réclamation',
    scenario:
      'You are customer support for an online shop. The learner received a damaged product.',
    objective: 'The customer explains the problem and requests a refund or replacement.',
    requiredVocab: ['I would like to complain', 'damaged', 'a refund', 'as soon as possible'],
    cefr: 'B1',
    turnLimit: 5,
    opener: 'Hello, thank you for contacting support. How can I help you today?',
  },
  {
    id: 'job-interview',
    title: "Entretien d'embauche",
    scenario: 'You are a hiring manager interviewing the learner for a junior role.',
    objective: 'The candidate states a strength and asks one question about the role.',
    requiredVocab: [
      'my strength is',
      'I have experience in',
      'could you tell me',
      'I am interested in',
    ],
    cefr: 'B2',
    turnLimit: 5,
    opener: 'Thanks for coming in today. To start, could you tell me a bit about yourself?',
  },
  {
    id: 'team-meeting',
    title: 'Donner son avis en réunion',
    scenario: 'You are leading a short team meeting. The learner is a team member.',
    objective: 'The learner gives an opinion on the plan and suggests one improvement.',
    requiredVocab: ['I think that', 'in my opinion', 'we could', 'I suggest'],
    cefr: 'B2',
    turnLimit: 5,
    opener: "Okay everyone — here's the plan for next week. What do you think?",
  },
  {
    id: 'doctor-appointment',
    title: 'Prendre rendez-vous médical',
    scenario: 'You are a receptionist at a medical clinic. The learner wants an appointment.',
    objective: 'The learner books an appointment and describes a symptom.',
    requiredVocab: ['I would like an appointment', 'I have a', 'available', 'thank you'],
    cefr: 'B1',
    turnLimit: 4,
    opener: 'Good morning, City Clinic, how can I help you?',
  },
  {
    id: 'small-talk-work',
    title: 'Small talk au travail',
    scenario: 'You are a colleague chatting with the learner near the coffee machine.',
    objective: 'The learner keeps the conversation going for a few exchanges about the weekend.',
    requiredVocab: ['how was your weekend', 'I went to', 'sounds great', 'what about you'],
    cefr: 'B1',
    turnLimit: 4,
    opener: 'Morning! Did you have a good weekend?',
  },
  {
    id: 'negotiate-price',
    title: 'Négocier un prix',
    scenario: 'You are a seller at a market stall. The learner wants to buy and negotiate.',
    objective: 'The buyer makes a counter-offer and reaches an agreement.',
    requiredVocab: ['how much is', 'that is too expensive', 'can you lower', 'it is a deal'],
    cefr: 'B1',
    turnLimit: 5,
    opener: "Hello, my friend! Beautiful bag, isn't it? Only fifty dollars for you.",
  },
  {
    id: 'phone-reschedule',
    title: 'Reporter un rendez-vous par téléphone',
    scenario: 'You answer the phone at an office. The learner needs to reschedule a meeting.',
    objective: 'The learner explains they cannot attend and proposes a new time.',
    requiredVocab: ['I am calling about', 'I am afraid', 'could we reschedule', 'does that work'],
    cefr: 'B2',
    turnLimit: 4,
    opener: 'Good morning, Brightline Office, how can I help you?',
  },
  {
    id: 'opinion-debate',
    title: 'Défendre une opinion',
    scenario: 'You are a friend having a friendly debate with the learner about remote work.',
    objective: 'The learner states and supports an opinion with at least one reason.',
    requiredVocab: ['I believe', 'on the other hand', 'for example', 'that is why'],
    cefr: 'C1',
    turnLimit: 5,
    opener: "Honestly, I think remote work makes people less productive. What's your take?",
  },
];

export function getMission(id: string): Mission | undefined {
  return ALL_MISSIONS.find((m) => m.id === id);
}
